Qrcode
ist-fwwb/user-android pull request #7
Opened 2019-02-01 17:11 UTC by ssingularity

加入了对于扫码会议室端二维码的结果处理

2019-02-01 17:30 UTC, TobbHuang requested changes

2019-02-01 17:30 UTC, TobbHuang commented on app/src/main/java/com/huangtao/user/fragment/MainFragmentA.java
> +                public void onResponse(Call<Meeting> call, Response<Meeting> response) {
这里通过meeting id拿到meeting的body，然后传入meeting room activity？

2019-02-01 17:33 UTC, ssingularity commented on app/src/main/java/com/huangtao/user/fragment/MainFragmentA.java
> +                public void onResponse(Call<Meeting> call, Response<Meeting> response) {
对的，会议室端app的二维码会传出会议室id，然后通过用户端app扫码，进入会议室预定页面

2019-02-02 05:09 UTC, TobbHuang commented on app/src/main/java/com/huangtao/user/fragment/MainFragmentA.java
> +                public void onResponse(Call<Meeting> call, Response<Meeting> response) {
那应该是请求meeting room啊，怎么是meeting?

2019-02-02 06:47 UTC, ssingularity commented on app/src/main/java/com/huangtao/user/fragment/MainFragmentA.java
> +                public void onResponse(Call<Meeting> call, Response<Meeting> response) {
哇，我的，写错了。。。
我改一下

2019-02-02 06:49 UTC, closed without merging